import { ThemeProvider } from "@/components/theme-provider"
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { TopMenuDesktop } from "@/app/navmenu";
import FileHandler from '@tiptap-pro/extension-file-handler'
import Image from '@tiptap/extension-image'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}><ThemeProvider
        attribute="class"
        defaultTheme="light"
        enableSystem
        disableTransitionOnChange
      >
      <TopMenuDesktop/>
        {children}
      </ThemeProvider></body>
    </html>
  );
}
